services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_URL=http://api-gateway:5000
    depends_on:
      - api-gateway

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "5000:5000"
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - PHOTO_SERVICE_URL=http://photo-service:5002
      - PROFILE_SERVICE_URL=http://profile-service:5003
      - TEMPLATE_SERVICE_URL=http://template-service:5004
      - SUBDOMAIN_SERVICE_URL=http://subdomain-service:5005
    depends_on:
      - user-service
      - photo-service
      - profile-service
      - template-service
      - subdomain-service

  user-service:
    build: ./services/user-service
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - REDIS_URI=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
      - redis

  photo-service:
    build: ./services/photo-service
    environment:
      - DATABASE_URI=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/photodb
      - REDIS_URI=redis://redis:6379/1
      - RABBITMQ_URI=${RABBITMQ_URI}
    depends_on:
      - postgres
      - redis
      - rabbitmq

  profile-service:
    build: ./services/profile-service
    environment:
      - DATABASE_URI=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/profiledb
      - REDIS_URI=redis://redis:6379/2
    depends_on:
      - postgres
      - redis

  template-service:
    build: ./services/template-service
    environment:
      - DATABASE_URI=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/templatedb
      - REDIS_URI=redis://redis:6379/3
    depends_on:
      - postgres
      - redis

  subdomain-service:
    build: ./services/subdomain-service
    environment:
      - DATABASE_URI=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/subdomaindb
      - REDIS_URI=redis://redis:6379/4
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
